### ISSUE TITLE
The settings menu jiggles when you click tabs

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#58] opened 2016-12-25 02:26 UTC
I mean it's probably an intended effect but it just looks really weird watching the menu jiggle when I click a different setting tab.

**Comment by paultech** [comment] 2016-12-25 02:29
It was intended :-( but concur it is a bit odd looking. Will see if I can tweak to get a better result or I'll remove it.

**Comment by paultech** [comment] 2016-12-27 18:24
No more jiggles :(
Fixed in 0.0.8

**Closed as completed by paultech** 2016-12-27 18:24 UTC
Labels: enhancement
